Repository COS301-SE-2025/Green-Cart, pull requests merged in 2025-06, with the labels that each got.

#84 Frontend help page
  frontend/src/App.jsx
  frontend/src/assets/images/help-green.avif
  frontend/src/pages/Cart.jsx
  frontend/src/pages/Help.jsx
  frontend/src/pages/styles/Cart.css
  frontend/src/pages/styles/Help.css
Labels: Integration

#93 89 order styling
  frontend/index.html
  frontend/public/green.svg
  frontend/src/pages/UserAccount.jsx
  frontend/src/pages/styles/UserAccount.css
Labels: enhancement

#94 87 integration of orders
  app/routes/orders.py
  app/services/cart.py
  app/services/orders_service.py
  frontend/src/cart-services/addToCart.js
  frontend/src/cart-services/removeFromCart.js
  frontend/src/cart-services/viewCart.js
  frontend/src/components/cart/CartContext.jsx
  frontend/src/components/product/ViewProduct.jsx
  frontend/src/order-services/cancelOrder.js
  frontend/src/order-services/createOrder.js
  frontend/src/order-services/fetchAllOrders.js
  frontend/src/pages/Cart.jsx
  frontend/src/pages/Checkout.jsx
  frontend/src/pages/Orders.jsx
Labels: Integration

#95 40 user settings api endpoint
  app/main.py
  app/models/address.py
  app/models/user.py
  app/routes/authentication.py
  app/routes/users.py
  app/schemas/user.py
  app/services/user_service.py
  frontend/src/pages/Orders.jsx
  frontend/src/pages/SearchResults.jsx
  frontend/src/pages/UserAccount.jsx
  frontend/src/pages/styles/UserAccount.css
  frontend/src/user-services/fetchUserInformation.js
Labels: enhancement, Integration
