Repository COS301-SE-2025/Green-Cart, pull requests merged in 2025-09, with the labels that each got.

#205 198 admin order overview integration
  app/main.py
  app/routes/admin_orders.py
  app/schemas/admin.py
  app/services/admin_overview_services.py
  frontend/src/components/admin/elements/OrdersStatsCard.jsx
  frontend/src/config/api.js
Labels: enhancement, Integration

#206 200 admin orders table integration
  app/routes/admin_orders.py
  app/schemas/admin.py
  app/services/admin_overview_services.py
  frontend/src/components/admin/elements/OrdersTable.jsx
  frontend/src/components/admin/tabs/Orders.jsx
Labels: enhancement, Integration

#211 196 admin monthly orders graph integration
  app/routes/admin_orders.py
  app/schemas/admin.py
  app/services/admin_overview_services.py
  frontend/src/components/admin/elements/DashboardMetricsChart.jsx
Labels: enhancement, Integration

#212 Refactor total retailers count query to group by user ID for accurate…
  app/routes/admin_metrics.py
Labels: bug

#213 208 mcp frontend styling
  app/main.py
  app/routes/recommendations.py
  app/routes/retailer_products.py
  app/services/mcp_structures.py
  app/services/openai_service.py
  app/services/product_service.py
  app/services/recommendation_engine.py
  frontend/src/components/admin/elements/OrdersTable.jsx
  frontend/src/components/admin/modals/AdminOrderDetailsModal.jsx
  frontend/src/components/admin/tabs/Orders.jsx
  frontend/src/components/login/LoginForm.jsx
  frontend/src/components/mcp/EcoMeterSummary.jsx
  frontend/src/components/mcp/LoadingStates.jsx
  frontend/src/components/mcp/RecommendationsStrip.jsx
  frontend/src/components/mcp/SustainabilityAI.jsx
  frontend/src/components/mcp/UnifiedLoading.jsx
  frontend/src/components/mcp/WhyRecommendedModal.css
  frontend/src/components/mcp/WhyRecommendedModal.jsx
  frontend/src/components/modals/ChangePasswordModal.jsx
  frontend/src/components/modals/TwoFactorModal.jsx
  frontend/src/components/modals/TwoFactorVerificationModal.jsx
  frontend/src/components/product/ViewProduct.jsx
  frontend/src/components/styles/admin/modals/AdminOrderDetailsModal.css
  frontend/src/components/styles/admin/tabs/Orders.css
  frontend/src/components/styles/mcp/mcp.css
  frontend/src/components/styles/modals/ChangePasswordModal.css
  frontend/src/components/styles/modals/TwoFactorModal.css
  frontend/src/components/styles/modals/TwoFactorVerificationModal.css
  frontend/src/components/styles/product/ViewProduct.css
  frontend/src/pages/Cart.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/UserAccount.jsx
  frontend/src/pages/styles/SearchResults.css
  frontend/src/services/mcpMockService.js
  frontend/src/services/mcpService.js
  frontend/src/utils/mcpTest.js
  requirements.txt
  uploads/.gitkeep
  uploads/images/6b0f43b8-a4ae-4444-9021-51abf944d47f.jpeg
  uploads/images/960eb936-052a-47f4-818b-015527d0dc21.jpeg
  uploads/images/b64d4274-90d5-4de7-a6f1-344623b91650.jpeg
Labels: enhancement

#214 199 admin revenue overview integration
  app/routes/admin_orders.py
  app/schemas/admin.py
  app/services/admin_overview_services.py
  frontend/src/components/admin/elements/OrdersStatsCard.jsx
Labels: enhancement, Integration

#227 190 two factor authentication
  app/models/user.py
  app/routes/admin_orders.py
  app/routes/users.py
  app/schemas/admin.py
  app/schemas/user.py
  app/services/admin_overview_services.py
  app/services/user_service.py
  frontend/src/components/admin/elements/OrdersStatsCard.jsx
  frontend/src/components/admin/modals/AdminOrderDetailsModal.jsx
  frontend/src/components/admin/tabs/Orders.jsx
Labels: bug, enhancement, Integration

#232 Dev
  app/main.py
  app/models/user.py
  app/routes/admin_metrics.py
  app/routes/admin_orders.py
  app/routes/authentication.py
  app/routes/users.py
  app/schemas/admin.py
  app/schemas/user.py
  app/services/admin_overview_services.py
  app/services/user_service.py
  frontend/src/components/admin/Login.jsx
  frontend/src/components/admin/SideBar.jsx
  frontend/src/components/admin/elements/DashboardMetricsChart.jsx
  frontend/src/components/admin/elements/OrdersStatsCard.jsx
  frontend/src/components/admin/elements/OrdersTable.jsx
  frontend/src/components/admin/modals/AdminOrderDetailsModal.jsx
  frontend/src/components/admin/tabs/Customers.jsx
  frontend/src/components/admin/tabs/Dashboard.jsx
  frontend/src/components/admin/tabs/Orders.jsx
  frontend/src/components/login/LoginForm.jsx
  frontend/src/components/mcp/RecommendationsStrip.jsx
  frontend/src/components/modals/ConfirmationModal.jsx
  frontend/src/components/modals/TwoFactorModal.jsx
  frontend/src/components/navigation/Navigation.jsx
  frontend/src/components/register/RegisterForm.jsx
  frontend/src/components/retailer/AddProduct.jsx
  frontend/src/components/retailer/EditProduct.jsx
  frontend/src/components/styles/admin/Login.css
  frontend/src/components/styles/admin/SideBar.css
  frontend/src/components/styles/admin/tabs/Orders.css
  frontend/src/components/styles/login/LoginForm.css
  frontend/src/components/styles/mcp/mcp.css
  frontend/src/components/styles/modals/ConfirmationModal.css
  frontend/src/components/styles/register/RegisterForm.css
  frontend/src/components/styles/retailer/AddProduct.css
  frontend/src/components/styles/retailer/EditProduct.css
  frontend/src/config/api.js
  frontend/src/index.css
  frontend/src/pages/Admin.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Splash.jsx
  frontend/src/pages/UserAccount.jsx
  frontend/src/pages/styles/SearchResults.css
  frontend/src/pages/styles/Splash.css
  frontend/src/test/components/login/LoginForm.test.jsx
  frontend/src/test/components/register/RegisterForm.test.jsx
  frontend/src/user-services/loginService.js
Labels: bug, enhancement, Integration

#241 236 polishing
  app/main.py
  app/routes/admin_products.py
  app/routes/authentication.py
  app/routes/recommendations.py
  app/services/carbon_forecasting.py
  app/services/openai_service.py
  app/services/recommendation_engine.py
  app/services/smart_structures.py
  app/services/user_service.py
  frontend/src/components/admin/ProductVerification.css
  frontend/src/components/admin/ProductVerification.jsx
  frontend/src/components/admin/elements/ProductVerification.jsx
  frontend/src/components/mcp/EcoMeterSummary.jsx
  frontend/src/components/product/ViewProduct.jsx
  frontend/src/components/smart/EcoMeterSummary.jsx
  frontend/src/components/smart/LoadingStates.jsx
  frontend/src/components/smart/RecommendationsStrip.jsx
  frontend/src/components/smart/SustainabilityAI.jsx
  frontend/src/components/smart/UnifiedLoading.jsx
  frontend/src/components/smart/WhyRecommendedModal.css
  frontend/src/components/smart/WhyRecommendedModal.jsx
  frontend/src/components/styles/login/LoginForm.css
  frontend/src/components/styles/product/ViewProduct.css
  frontend/src/components/styles/register/RegisterForm.css
  frontend/src/components/styles/smart/smart.css
  frontend/src/pages/Cart.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/RetailerAuth.jsx
  frontend/src/services/smartMockService.js
  frontend/src/services/smartService.js
  frontend/src/user-services/userCheckService.js
  frontend/src/utils/smartTest.js
  test_email_system.py
Labels: bug, enhancement

#246 2 fa hot fix
  frontend/src/components/modals/TwoFactorModal.jsx
  frontend/src/pages/UserAccount.jsx
Labels: bug, enhancement

#248 247 final polishing and fixes
  app/routes/carbon_forecasting.py
  app/routes/retailer_products.py
  app/schemas/carbon_forecasting.py
  app/services/carbon_forecasting.py
  app/services/retailer_products_services.py
  frontend/src/components/modals/HelpModal.css
  frontend/src/components/modals/HelpModal.jsx
  frontend/src/components/retailer/Auth/RetailerAuthOverlay.jsx
  frontend/src/components/retailer/EditProduct.jsx
  frontend/src/components/retailer/ProductCarousel.jsx
  frontend/src/components/styles/retailer/EditProduct.css
  frontend/src/components/styles/retailer/ProductCarousel.css
  frontend/src/pages/Login.jsx
  frontend/src/pages/Register.jsx
  frontend/src/pages/RetailerAuth.jsx
  frontend/src/pages/RetailerProducts.jsx
  frontend/src/pages/UserAccount.jsx
  frontend/src/pages/ViewRetailerProduct.jsx
  frontend/src/pages/styles/RetailerProducts.css
  frontend/src/pages/styles/UserAccount.css
  frontend/src/pages/styles/ViewRetailerProduct.css
  frontend/src/services/forecastingService.js
  frontend/src/user-services/retailerAuthService.js
Labels: bug, enhancement, Integration

#251 Dev
  EMAIL_TESTING_COMMANDS.md
  app/routes/recommendations.py
  app/routes/test_email.py
  app/services/openai_service.py
  app/services/recommendation_engine.py
  app/services/smart_structures.py
  app/services/user_service.py
  frontend/src/components/admin/elements/ProductVerification.jsx
  frontend/src/components/admin/icons/pencilIcon.png
  frontend/src/components/admin/icons/process.png
  frontend/src/components/admin/icons/verificationIcon.png
  frontend/src/components/admin/tabs/Products.jsx
  frontend/src/components/smart/EcoMeterSummary.jsx
  frontend/src/components/smart/LoadingStates.jsx
  frontend/src/components/smart/UnifiedLoading.jsx
  frontend/src/components/smart/WhyRecommendedModal.css
  frontend/src/components/smart/WhyRecommendedModal.jsx
  frontend/src/components/styles/admin/ProductVerification.css
  frontend/src/components/styles/admin/tabs/Products.css
  frontend/src/components/styles/modals/TwoFactorModal.css
  frontend/src/components/styles/smart/smart.css
  frontend/src/pages/Help.jsx
  frontend/src/pages/styles/SearchResults.css
  frontend/src/services/smartMockService.js
  frontend/src/services/smartService.js
  frontend/src/user-services/userCheckService.js
  frontend/src/utils/smartTest.js
  requirements.txt
Labels: bug, enhancement

#256 255 readme and documentation fixes
  .dockerignore
  Dockerfile
  app/assets/bab0a241-abac-4c89-85cd-100c4b053fb6/banner.png
  app/assets/bab0a241-abac-4c89-85cd-100c4b053fb6/image.png
  app/data/retailers.json
  docs/base64_storage_analysis.py
  frontend/login_debug.png
  frontend/playwright-report/data/64c0c609acf9fde4253ea48b9ce9a92d37c405a9.webm
  frontend/playwright-report/index.html
  frontend/test-results/.last-run.json
  frontend/test-results/cart-flow-user-logs-in-and-adds-product-to-cart/video.webm
  uploads/.gitkeep
Labels: enhancement
